# Generated by Django 5.2.8 on 2025-12-05 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message_deleted_at_alter_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 5, 17, 52, 17, 479692, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 5, 17, 52, 17, 480743, tzinfo=datetime.timezone.utc)),
        ),
    ]
