# Generated by Django 5.2.8 on 2025-12-05 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_conversation_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageDeletions',
            new_name='MessageDeletion',
        ),
        migrations.RenameIndex(
            model_name='messagedeletion',
            new_name='chatapp_mes_user_id_c2efd6_idx',
            old_name='chatapp_mes_user_id_ac0fbb_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
